export class ClientDetails{
    UserId: number;
    IdentityUserId: number;
    ClientProfileId: number;
    Fname: string;
    Mname: string;
    Lname: string;
    UserName:string;
    PasswordHash:string;
    DOB: Date | null;
    Gender: string;
    PANNo: string;
    AadharNo: string;
    EmailId: string;
    MobileNo: string;
    PhoneNo: string;
    Pincode: string;
    FlatDoor: string;
    BuildingName: string;
    RoadStreet: string;
    AreaLocality: string;
    District: string;
    CountryId: number;
    Country: number;
    StateId: number;
    State: number;
    ZipCode: string;
    Remark: string;
    CorporateName: string;
    OrganizationName: string;
    OrganizationId:number;
    CompanyName: string;
    CompanyUrl: string;
    CompanyPan: string;
    CompanyTan: string;
    AddedBy: number;
    AddedDate: Date | null;
    UpdatedBy: number | null;
    UpdatedDate: Date | null;
    IsActive: boolean | null;
}